apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: daemonset
  template:
    metadata:
      labels:
        name: daemonset
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: logdir
          mountPath: /nodes-logs/syslog
          subPath: syslog
        - name: varlog
          mountPath: /var/log/syslog
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logdir
        hostPath:
          path: /var/log
      - name: varlog
        hostPath:
          path: /var/log
